server:
  port: 10030
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 222.186.21.38:8848
    gateway:
      metrics:
        enabled: true
      routes:
        - id: order-service #路由规则,随便起,不重复
          uri: lb://order-service/ #目标服务地址
          predicates: #路由条件
            - Path=/order/**,/feign/**
            - After=2024-11-12T15:29:35.480689900+08:00[Asia/Shanghai]
          filters:
            - AddRequestParameter=userName, root
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
      default-filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
