spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?characterEncoding=utf8&useSSL=false
    username: root
    password: TEST@yyds.666
    driver-class-name: com.mysql.cj.jdbc.Driver